"use strict";var settings={preloaderBackground:"#222",progressSize:400,progressColor:"#00FFFF",progressOpacity:.5,textColor:"#00FFFF",textOpacity:.5,lineWidth:4,lineCap:"round",preloaderAnimationDuration:1E3,startDegree:-90,finalDegree:270};function setAttributes(a,b){for(var c in b)a.setAttribute(c,b[c])}var preloader=document.createElement("div"),canvas=document.createElement("canvas"),progressPercentage=document.createElement("div"),size;
(function(){var a=window.innerWidth,b=window.innerHeight;size=a>b?Math.min(settings.progressSize,b/2):Math.min(settings.progressSize,a-50)})();setAttributes(preloader,{"class":"preloader",id:"preloader",style:"transition: opacity "+settings.preloaderAnimationDuration/1E3+"s"});setAttributes(canvas,{"class":"preloader__progress-bar",id:"progress-bar",width:size,height:size});setAttributes(progressPercentage,{"class":"preloader__progress-percentage",id:"progress-percentage"});
document.body.insertBefore(preloader,document.body.firstChild);preloader.appendChild(canvas);preloader.appendChild(progressPercentage);preloader=document.getElementById("preloader");progressPercentage=document.getElementById("progress-percentage");
var progressBar=document.getElementById("progress-bar"),images=document.images,imagesAmount=images.length,imagesLoaded=0,barCtx=progressBar.getContext("2d"),circleCenterX=progressBar.width/2,circleCenterY=progressBar.height/2,circleRadius=circleCenterX-settings.lineWidth,degreesPerPercent=3.6,currentProgress=0,showedProgress=0,progressStep=0,progressDelta=0,startTime=null,running;
(function(){return requestAnimationFrame||mozRequestAnimationFrame||webkitRequestAnimationFrame||oRequestAnimationFrame||msRequestAnimationFrame||function(a){setTimeout(a,1E3/60)}})();Math.radians=function(a){return a*Math.PI/180};progressPercentage.style.color=settings.textColor;progressPercentage.style.opacity=settings.textOpacity;progressBar.style.opacity=settings.progressOpacity;barCtx.strokeStyle=settings.progressColor;barCtx.lineWidth=settings.lineWidth;barCtx.lineCap=settings.lineCap;
var angleMultiplier=(Math.abs(settings.startDegree)+Math.abs(settings.finalDegree))/360,startAngle=Math.radians(settings.startDegree);document.body.style.overflowY="hidden";preloader.style.backgroundColor=settings.preloaderBackground;if(0<imagesAmount)for(var i=0;i<imagesAmount;i++){var imageClone=new Image;imageClone.onload=onImageLoad;imageClone.onerror=onImageLoad;imageClone.src=images[i].src}else currentProgress=100,progressStep=0,progressDelta=100,startTime=performance.now(),animate(),hidePreloader();
function onImageLoad(){!0===running&&(running=!1);imagesLoaded++;imagesLoaded>=imagesAmount&&hidePreloader();progressStep=showedProgress;currentProgress=100/imagesAmount*imagesLoaded<<0;progressDelta=Math.ceil(currentProgress-showedProgress);setTimeout(function(){null===startTime&&(startTime=performance.now());running=!0;animate()},10)}
function animate(){if(!1===running)startTime=null;else{var a=Math.min(1,(performance.now()-startTime)/settings.preloaderAnimationDuration);showedProgress=Math.ceil(progressStep+progressDelta*a);1>a?(progressPercentage.innerHTML=Math.ceil(showedProgress),barCtx.clearRect(0,0,progressBar.width,progressBar.height),barCtx.beginPath(),barCtx.arc(circleCenterX,circleCenterY,circleRadius,startAngle,Math.radians(showedProgress*degreesPerPercent)*angleMultiplier+startAngle),barCtx.stroke(),requestAnimationFrame(animate)):
startTime=null}}function hidePreloader(){setTimeout(function(){preloader.classList.add("preloader_unvisible");document.body.style.overflowY=""},settings.preloaderAnimationDuration+100)}
var contentColumns=document.getElementsByClassName("slide__content"),slideActive=document.querySelector(".slide_active"),navigation=document.querySelector(".navigation"),btnAbout=document.getElementById("button-about"),parallaxMeasure=150,parallaxCenterX=window.innerWidth/2,parallaxCenterY=window.innerHeight/2,parallaxObj=document.getElementsByClassName("parallax"),styles=document.getElementById("responsive-styles"),href,burgerClickArea=document.getElementById("click-area"),burger=document.getElementById("burger"),
list=document.getElementById("list"),listItems=document.getElementsByClassName("menu__item"),aboutMeLink=document.querySelector(".about-me-link"),slider=document.getElementById("slider"),slides=document.getElementsByClassName("slide"),dots=document.getElementsByClassName("navigation-item"),wrapper=document.getElementById("wrapper"),btnDown=document.getElementById("button-godown"),btnMore=document.getElementsByClassName("more-button"),secAbout=document.querySelector(".about"),secAboutClose=document.querySelector(".about .close"),
colored=secAbout.querySelectorAll(".colored"),filter=document.querySelector(".slider .filter"),backgrounds=document.getElementsByClassName("slide__content-column"),currentSlide=0,slidesAmount=slides.length,sliderAnimationDuration=1E3*parseFloat(window.getComputedStyle(wrapper).getPropertyValue("transition-duration"))||800,touched=!1,counter=0,touchSensitivity=4,initPos,curPos;
function parallax(a){a="translate("+Math.round((parallaxCenterX-a.clientX)/parallaxMeasure)+"px, "+Math.round((parallaxCenterY-a.clientY)/parallaxMeasure)+"px)";contentColumns[currentSlide].style.transform=a;btnAbout.style.transform=a;btnDown.style.transform=a;navigation.style.transform=a}function resetParallax(){for(var a=0;a<parallaxObj.length;a++)parallaxObj[a].style.transform="translate( 0px, 0px )"}
(function(){window.onload=function(){var a;0<navigator.userAgent.search(/Safari/)&&(a="Safari");0<navigator.userAgent.search(/Firefox/)&&(a="MozillaFirefox");if(0<navigator.userAgent.search(/MSIE/)||0<navigator.userAgent.search(/NET CLR /))a="Internet Explorer";0<navigator.userAgent.search(/Chrome/)&&(a="Google Chrome");0<navigator.userAgent.search(/YaBrowser/)&&(a="\u042f\u043d\u0434\u0435\u043a\u0441 \u0431\u0440\u0430\u0443\u0437\u0435\u0440");0<navigator.userAgent.search(/OPR/)&&(a="Opera");0<
navigator.userAgent.search(/Konqueror/)&&(a="Konqueror");0<navigator.userAgent.search(/Iceweasel/)&&(a="Debian Iceweasel");0<navigator.userAgent.search(/SeaMonkey/)&&(a="SeaMonkey");0<navigator.userAgent.search(/Edge/)&&(a="Edge");if(!("Internet Explorer"!==a&&"Edge"!==a||"MozillaFirefox"==a&&"Opera"==a)){a=document.getElementsByClassName("slide__content-column");for(var b=0;b<a.length;b++)a[b].classList.add("slide__content-column_no-bg-blend")}};window.onresize=changeHref;changeHref()})();
function changeHref(){var a=window.innerWidth;767>=a&&"css/styles_max_767.css"!=href?(href=styles.href="css/styles_max_767.css",slider.onmousemove=null,resetParallax()):768<=a&&1023>=a&&"css/styles_min_768.css"!=href?(href=styles.href="css/styles_min_768.css",slider.onmousemove=null,resetParallax()):1024<=a&&"css/styles_min_1024.css"!=href&&(href=styles.href="css/styles_min_1024.css",slider.onmousemove=parallax)}
burgerClickArea.onclick=function(){burger.classList.contains("burger_active")?(restyleMenu(!0),setTimeout(function(){burger.classList.toggle("burger_active")},170)):(setTimeout(function(){restyleMenu()},270),burger.classList.toggle("burger_active"))};aboutMeLink.onclick=function(){secAbout.classList.add("about_active");restyleMenu(!0);setTimeout(function(){burger.classList.toggle("burger_active")},170)};
function restyleMenu(a){if(a)var b=listItems.length-1,c=setInterval(function(){0<=b?(listItems[b].classList.toggle("menu__item_visible"),b--):clearInterval(c)},800/listItems.length);else var d=0,e=setInterval(function(){d<listItems.length?(listItems[d].classList.toggle("menu__item_visible"),d++):clearInterval(e)},500/listItems.length)}
function showHeading(){var a=document.querySelector(".slide_active .heading"),b=0;setInterval(function(){if(b<a.children.length)a.children[b].classList.toggle("visible"),b++;else return!1},800/a.children.length)}function hideHeading(){for(var a=document.querySelector(".slide_active .heading"),b=0;b<a.children.length;b++)a.children[b].classList.toggle("visible")}function hasEvent(a,b){return"on"+a in b}
(function(){showHeading();setupNavigationEvents();for(var a=0;a<dots.length;a++)dots[a].onclick=function(){wrapper.style.transitionDuration=sliderAnimationDuration+"ms";var a=parseFloat(wrapper.style.getPropertyValue("top")),c=this.firstElementChild.href.split("#")[1];c=Math.round(document.querySelector("[ name =  "+c+" ]").offsetTop/window.innerHeight)-Math.abs(a/100);currentSlide+=c;wrapper.style.top=a-100*c+"vh";reStyle()};hasEvent("touchstart",wrapper)?wrapper.ontouchstart=function(a){touched=
!0;initPos=a.touches[0].pageY}:wrapper.onpointerdown=function(a){touched=!0;initPos=a.clientY};hasEvent("touchend",wrapper)?wrapper.ontouchend=function(){touched=!1;initPos=null}:wrapper.onpointerup=function(){touched=!1;initPos=null};for(a=0;a<btnMore.length;a++)btnMore[a].onmouseover=function(){filter.classList.add("filter_light")},btnMore[a].onmouseleave=function(){filter.classList.remove("filter_light")};btnAbout.onclick=function(){secAbout.classList.add("about_active")};secAboutClose.onclick=
function(){secAbout.classList.remove("about_active")}})();function setupNavigationEvents(){wrapper.addEventListener?wrapper.addEventListener("wheel",onWheel,!1):"";btnDown.onclick=function(){wrapper.removeEventListener&&wrapper.removeEventListener("wheel",onWheel,!1);btnDown.onclick=null;listener(1)};hasEvent("touchmove",wrapper)?wrapper.ontouchmove=detectScrollDirection:wrapper.onpointermove=detectScrollDirection}
function detectScrollDirection(a){if(touched){a=a||window.event;counter++;var b;if("touchmove"===a.type&&counter>=touchSensitivity){counter=0;wrapper.removeEventListener&&(wrapper.ontouchmove=function(a){c=initPos=a.touches[0].pageY});var c=a.touches[0].pageY;0<c-initPos?b=-1:b=1;listener(b)}else if("pointermove"===a.type&&counter>=touchSensitivity){counter=0;wrapper.removeEventListener&&(wrapper.onpointermove=function(a){d=initPos=a.clientY});var d=a.clientY;0<d-initPos?b=-1:b=1;listener(b)}}}
function onWheel(a){a=a||window.event;wrapper.removeEventListener&&wrapper.removeEventListener("wheel",onWheel,!1);var b=a.deltaY||a.detail||a.wheelDelta;b!=a.wheelDelta?0>b?b=-1:b=1:0>b?b=1:b=-1;listener(b)}
function listener(a){wrapper.style.transitionDuration="0s";0===currentSlide&&0>a?(currentSlide=slidesAmount-1,wrapper.style.top="-100vh",wrapper.insertBefore(wrapper.lastElementChild,wrapper.firstElementChild),setTimeout(function(){animateWrapper(!1,!0,a);reStyle(0)},20)):currentSlide===slidesAmount-1&&0<a?(currentSlide=0,wrapper.style.top=-100*(slidesAmount-2)+"vh",wrapper.appendChild(wrapper.firstElementChild),setTimeout(function(){animateWrapper(!0,!1,a);reStyle(slidesAmount-1)},20)):(currentSlide+=
a,reStyle(),setTimeout(function(){animateWrapper(!1,!1,a)},20))}
function animateWrapper(a,b,c){setTimeout(setupNavigationEvents,sliderAnimationDuration+20);wrapper.style.transitionDuration=sliderAnimationDuration+"ms";b?(wrapper.style.top="0vh",setTimeout(function(){wrapper.style.transitionDuration="0s";for(var a=0;a<slidesAmount-1;a++){var b=parseFloat(wrapper.style.getPropertyValue("top"));wrapper.insertBefore(wrapper.lastElementChild,wrapper.firstElementChild);wrapper.style.top=b+100*c+"vh"}},sliderAnimationDuration)):a?(wrapper.style.top=-100*(slidesAmount-
1)+"vh",setTimeout(function(){wrapper.style.transitionDuration="0s";for(var a=0;a<slidesAmount-1;a++){var b=parseFloat(wrapper.style.getPropertyValue("top"));wrapper.appendChild(wrapper.firstElementChild);wrapper.style.top=b+100*c+"vh"}},sliderAnimationDuration)):(a=parseFloat(wrapper.style.getPropertyValue("top")),wrapper.style.top=a-100*c+"vh")}
function reStyle(a){hideHeading();var b;null!=a?b=backgrounds[a].getAttribute("data-color"):b=backgrounds[currentSlide].getAttribute("data-color");document.querySelector(".slide_active .slide__content-column").style.backgroundColor=b;document.querySelector(".slide_active").classList.remove("slide_active");document.querySelector(".navigation-item_active").classList.remove("navigation-item_active");dots[currentSlide].classList.add("navigation-item_active");secAbout.querySelector(".photo-holder").style.backgroundColor=
b;for(var c=0;c<colored.length;c++)colored[c].style.color=b;null!=a?(slides[a].classList.add("slide_active"),backgrounds[a].style.backgroundColor=b):(slides[currentSlide].classList.add("slide_active"),backgrounds[currentSlide].style.backgroundColor=b);burger.style.backgroundColor=b;showHeading()};